# Portainer server services, contains server and agent
# Start: docker compose up -d
# Stop: docker compose down --volumes

version: '3.9'

networks:
  portainer-network:
    name: portainer-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.10.0/24
          gateway: 172.29.10.254
    enable_ipv6: false

services:
  server:
    container_name: portainer-server
    image: ${PortainerServerImage:?err}
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - ${PortainerDataPath:?err}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer-network
    dns:
      - 45.90.28.29
      - 45.90.30.29
    restart: unless-stopped

  agent:
    container_name: portainer-agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    restart: unless-stopped
    stdin_open: true
    tty: true