version: '3.9'

services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    restart: unless-stopped
    stdin_open: true
    tty: true